// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Documentation Page documents */
interface DocumentationPageDocumentData {
    /**
     * Page title field in *Documentation Page*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Page title
     * - **API ID Path**: documentation_page.page_title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    page_title: prismicT.TitleField;
    /**
     * Main text field in *Documentation Page*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Main content
     * - **API ID Path**: documentation_page.main_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    main_text: prismicT.RichTextField;
    /**
     * Slice Zone field in *Documentation Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: documentation_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<DocumentationPageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Documentation Page → Slice Zone*
 *
 */
type DocumentationPageDocumentDataSlicesSlice = EmbedSlice | HeaderSlice | ImageSlice | RichTextSlice;
/**
 * Documentation Page document from Prismic
 *
 * - **API ID**: `documentation_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DocumentationPageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<DocumentationPageDocumentData>, "documentation_page", Lang>;
/** Content for Homepage documents */
interface HomepageDocumentData {
    /**
     * Slice Zone field in *Homepage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomepageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Homepage → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice = PageHeaderSlice | HeaderSlice;
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomepageDocumentData>, "homepage", Lang>;
/** Content for Main Header documents */
interface MainHeaderDocumentData {
    /**
     * Logo field in *Main Header*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: main_header.logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<null>;
    /**
     * Internal Nav field in *Main Header*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: main_header.InternalNav[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    InternalNav: prismicT.GroupField<Simplify<MainHeaderDocumentDataInternalNavItem>>;
    /**
     * External Nav field in *Main Header*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: main_header.ExternalNav[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    ExternalNav: prismicT.GroupField<Simplify<MainHeaderDocumentDataExternalNavItem>>;
    /**
     * Slice Zone field in *Main Header*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: main_header.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<MainHeaderDocumentDataSlicesSlice>;
}
/**
 * Item in Main Header → Internal Nav
 *
 */
export interface MainHeaderDocumentDataInternalNavItem {
    /**
     * Nav Item field in *Main Header → Internal Nav*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: main_header.InternalNav[].NavItem
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    NavItem: prismicT.RelationField;
}
/**
 * Item in Main Header → External Nav
 *
 */
export interface MainHeaderDocumentDataExternalNavItem {
    /**
     * Nav Item field in *Main Header → External Nav*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: main_header.ExternalNav[].NavItem
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    NavItem: prismicT.LinkField;
}
/**
 * Slice for *Main Header → Slice Zone*
 *
 */
type MainHeaderDocumentDataSlicesSlice = never;
/**
 * Main Header document from Prismic
 *
 * - **API ID**: `main_header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MainHeaderDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<MainHeaderDocumentData>, "main_header", Lang>;
export type AllDocumentTypes = DocumentationPageDocument | HomepageDocument | MainHeaderDocument;
/**
 * Primary content in Embed → Primary
 *
 */
interface EmbedSliceDefaultPrimary {
    /**
     * Embed field in *Embed → Primary*
     *
     * - **Field Type**: Embed
     * - **Placeholder**: Loom, YouTube, etc. URL
     * - **API ID Path**: embed.primary.Embed
     * - **Documentation**: https://prismic.io/docs/core-concepts/embed
     *
     */
    Embed: prismicT.EmbedField;
}
/**
 * Default variation for Embed Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Embed`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type EmbedSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<EmbedSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Embed*
 *
 */
type EmbedSliceVariation = EmbedSliceDefault;
/**
 * Embed Shared Slice
 *
 * - **API ID**: `embed`
 * - **Description**: `Embed`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type EmbedSlice = prismicT.SharedSlice<"embed", EmbedSliceVariation>;
/**
 * Primary content in Header → Primary
 *
 */
interface HeaderSliceDefaultPrimary {
    /**
     * Logo field in *Header → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: header.primary.Logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    Logo: prismicT.ImageField<null>;
}
/**
 * Item in Header → Items
 *
 */
export interface HeaderSliceDefaultItem {
    /**
     * External Link field in *Header → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: header.items[].ExternalLink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    ExternalLink: prismicT.LinkField;
    /**
     * Internal Link field in *Header → Items*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: header.items[].InternalLink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    InternalLink: prismicT.RelationField;
}
/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Header`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeaderSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeaderSliceDefaultPrimary>, Simplify<HeaderSliceDefaultItem>>;
/**
 * Slice variation for *Header*
 *
 */
type HeaderSliceVariation = HeaderSliceDefault;
/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: `Header`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeaderSlice = prismicT.SharedSlice<"header", HeaderSliceVariation>;
/**
 * Primary content in Image → Primary
 *
 */
interface ImageSliceDefaultPrimary {
    /**
     * Image field in *Image → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: image.primary.Image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    Image: prismicT.ImageField<null>;
    /**
     * Image Link field in *Image → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: image.primary.ImageLink
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    ImageLink: prismicT.LinkField;
}
/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Image`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ImageSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Image*
 *
 */
type ImageSliceVariation = ImageSliceDefault;
/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: `Image`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageSlice = prismicT.SharedSlice<"image", ImageSliceVariation>;
/**
 * Primary content in PageHeader → Primary
 *
 */
interface PageHeaderSliceDefaultPrimary {
    /**
     * Title field in *PageHeader → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: page_header.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *PageHeader → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Description of page
     * - **API ID Path**: page_header.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for PageHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: `PageHeader`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PageHeaderSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<PageHeaderSliceDefaultPrimary>, never>;
/**
 * Slice variation for *PageHeader*
 *
 */
type PageHeaderSliceVariation = PageHeaderSliceDefault;
/**
 * PageHeader Shared Slice
 *
 * - **API ID**: `page_header`
 * - **Description**: `PageHeader`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type PageHeaderSlice = prismicT.SharedSlice<"page_header", PageHeaderSliceVariation>;
/**
 * Primary content in RichText → Primary
 *
 */
interface RichTextSliceDefaultPrimary {
    /**
     * WYSIWYG field in *RichText → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: rich_text.primary.wysiwyg
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    wysiwyg: prismicT.RichTextField;
}
/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: `RichText`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type RichTextSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<RichTextSliceDefaultPrimary>, never>;
/**
 * Slice variation for *RichText*
 *
 */
type RichTextSliceVariation = RichTextSliceDefault;
/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: `RichText`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type RichTextSlice = prismicT.SharedSlice<"rich_text", RichTextSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
}
