// This file is generated by Slice Machine. Update with care!

import Embed from './Embed';
import Header from './Header';
import Heading from './Heading';
import PageHeader from './PageHeader';
import PrismicImage from './PrismicImage';
import RichText from './RichText';
import TableBlock from './TableBlock';

export {
	Embed,
	Header,
	Heading,
	PageHeader,
	PrismicImage,
	RichText,
	TableBlock,
};

export const components = {
	embed: Embed,
	header: Header,
	heading: Heading,
	page_header: PageHeader,
	image: PrismicImage,
	rich_text: RichText,
	table_block: TableBlock,
};
