// This file is generated by Slice Machine. Update with care!

import Header from './Header';
import PageHeader from './PageHeader';

export {
	Header,
	PageHeader,
};

export const components = {
	header: Header,
	page_header: PageHeader,
};
