// This file is generated by Slice Machine. Update with care!

import Embed from './Embed';
import Header from './Header';
import Image from './Image';
import PageHeader from './PageHeader';
import RichText from './RichText';

export {
	Embed,
	Header,
	Image,
	PageHeader,
	RichText,
};

export const components = {
	embed: Embed,
	header: Header,
	image: Image,
	page_header: PageHeader,
	rich_text: RichText,
};
